import JSZip from "jszip";
import { PRODUCT_DISPLAY_NAME } from "@/config/productBrand";
import {
  buildCustomersExport,
  buildOutstandingExport,
  buildProductsExport,
  buildPurchasesRegisterExport,
  buildSalesLinesExport,
  buildSalesRegisterExport,
  buildStockSnapshotExport,
  buildVatPeriodSummaryExport,
  CUSTOMER_COLUMNS,
  OUTSTANDING_COLUMNS,
  PRODUCT_COLUMNS,
  PURCHASE_REGISTER_COLUMNS,
  SALES_LINES_COLUMNS,
  SALES_REGISTER_COLUMNS,
  STOCK_COLUMNS,
  VAT_SUMMARY_COLUMNS,
} from "./buildRegisters";
import { rowsToCsv } from "./csv";
import type { ExportDateRange } from "./types";

function ymd(d = new Date()): string {
  return d.toISOString().slice(0, 10);
}

export async function downloadFullBackupZip(range: ExportDateRange): Promise<void> {
  const stamp = ymd();
  const zip = new JSZip();
  const readme = `Tenant backup ${stamp}\nGenerated by ${PRODUCT_DISPLAY_NAME} export.\nPeriod: ${range.from} to ${range.to}\n`;
  zip.file("README.txt", readme);
  zip.file(
    "manifest.json",
    JSON.stringify({ exported_at: new Date().toISOString(), period: range }, null, 2),
  );

  const masters = await Promise.all([
    buildProductsExport(true),
    buildCustomersExport(),
    buildStockSnapshotExport(),
    buildOutstandingExport(),
  ]);
  zip.file("masters/products.csv", rowsToCsv(masters[0], [...PRODUCT_COLUMNS]));
  zip.file("masters/customers.csv", rowsToCsv(masters[1], [...CUSTOMER_COLUMNS]));
  zip.file("masters/stock_snapshot.csv", rowsToCsv(masters[2], [...STOCK_COLUMNS]));
  zip.file("masters/customer_outstanding.csv", rowsToCsv(masters[3], [...OUTSTANDING_COLUMNS]));

  const [salesReg, salesLines, purchases, vat] = await Promise.all([
    buildSalesRegisterExport(range),
    buildSalesLinesExport(range),
    buildPurchasesRegisterExport(range),
    buildVatPeriodSummaryExport(range),
  ]);
  zip.file("registers/sales_register.csv", rowsToCsv(salesReg, [...SALES_REGISTER_COLUMNS]));
  zip.file("registers/sales_lines.csv", rowsToCsv(salesLines, [...SALES_LINES_COLUMNS]));
  zip.file("registers/purchases_register.csv", rowsToCsv(purchases, [...PURCHASE_REGISTER_COLUMNS]));
  zip.file("registers/vat_period_summary.csv", rowsToCsv(vat, [...VAT_SUMMARY_COLUMNS]));

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `backup-${stamp}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
